---
- hosts: all
  remote_user: cumulus
  gather_facts: no
  become: yes
  tasks:
    - name: Write Hostname 
      shell: echo "{{ ansible_host }}" > /etc/hostname

    - name: Apply Hostname
      shell: hostname -F /etc/hostname

    - name: Add Local DNS Resolution for our Hostname
      lineinfile: dest=/etc/hosts line="127.0.1.1    {{inventory_hostname}}" regexp=^.*127.0.1.1
